"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import Link from "next/link";
import { useEffect, useState } from "react";
import { collection, deleteDoc, doc, getDocs, serverTimestamp, setDoc, writeBatch } from "firebase/firestore";
import { useRouter } from "next/navigation";
import { db } from "@/lib/firebase";
import { useAuth } from "@/hooks/useAuth";
import { statusLabel, type PartnerRegistration } from "@/lib/partner";

interface Ticket { id:string; subject:string; message:string; status:string; createdBy:string; createdByRole?:string; adminResponse?:string; }
interface StaffUser { id:string; displayName?:string; phoneNumber?:string; email?:string; role?:string; }
export default function PartnerAdminPage(){
 const {user,loading}=useAuth(); const router=useRouter(); const [rows,setRows]=useState<PartnerRegistration[]>([]); const [tickets,setTickets]=useState<Ticket[]>([]); const [staffUsers,setStaffUsers]=useState<StaffUser[]>([]); const [notice,setNotice]=useState("");
 const load=async()=>{if(!db)return;const[a,b,c,d2,e]=await Promise.all([getDocs(collection(db,"partnerOnboarding")),getDocs(collection(db,"supportTickets")),getDocs(collection(db,"users")),getDocs(collection(db,"customers")),getDocs(collection(db,"salesExecutives"))]);setRows(a.docs.map(d=>({id:d.id,...d.data()} as PartnerRegistration)));setTickets(b.docs.map(d=>({id:d.id,...d.data()} as Ticket)));const merged=new Map<string,StaffUser>();c.docs.forEach(item=>{const data=item.data() as Omit<StaffUser,"id">;if(data.role==="customer"||data.role==="sales_executive")merged.set(item.id,{id:item.id,...data});});d2.docs.forEach(item=>merged.set(item.id,{id:item.id,role:"customer",...(item.data() as Omit<StaffUser,"id"|"role">)}));e.docs.forEach(item=>merged.set(item.id,{id:item.id,role:"sales_executive",...(item.data() as Omit<StaffUser,"id"|"role">)}));setStaffUsers(Array.from(merged.values()));};
 useEffect(()=>{if(!loading&&user?.role!=="admin")router.replace("/");else if(user?.role==="admin")void load();},[loading,user?.role]);
 const decide=async(row:PartnerRegistration,status:"approved"|"rejected")=>{if(!db||!user)return; if(status==="approved"&&!row.ownerUid){setNotice("Vendor must verify OTP ownership before approval.");return;} const reason=status==="rejected"?(window.prompt("Reason for rejection")||"Not approved"):"";const batch=writeBatch(db);batch.update(doc(db,"partnerOnboarding",row.id),{status,rejectionReason:reason,approvedBy:user.uid,updatedAt:serverTimestamp()});if(status==="approved"&&row.ownerUid){batch.set(doc(db,"vendors",row.id),{userId:row.ownerUid,businessName:row.businessName,ownerName:row.ownerName,phone:row.phoneE164,city:row.city,address:row.address||"",category:row.category,verificationStatus:"Approved",leadStage:"Approved",source:"assisted_registration",partnerRegistrationId:row.id,approvedBy:user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});batch.set(doc(db,"vendorAccounts",row.ownerUid),{vendorId:row.id,phoneNumber:row.phoneE164,updatedAt:serverTimestamp()},{merge:true});}await batch.commit();setNotice(status==="approved"?"Vendor approved and portal activated.":"Registration rejected.");await load();};
 const closeTicket=async(t:Ticket)=>{if(!db)return;const response=window.prompt("Support response",t.adminResponse||"")||"Resolved by support.";const batch=writeBatch(db);batch.update(doc(db,"supportTickets",t.id),{status:"resolved",adminResponse:response,updatedAt:serverTimestamp()});await batch.commit();await load();};
 const setSalesRole=async(staff:StaffUser,enabled:boolean)=>{if(!db)return;if(enabled){await setDoc(doc(db,"salesExecutives",staff.id),{displayName:staff.displayName??null,phoneNumber:staff.phoneNumber??null,email:staff.email??null,promotedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});}else{await deleteDoc(doc(db,"salesExecutives",staff.id));}setNotice(enabled?"Sales-executive access activated.":"Sales-executive access removed.");await load();};
 if(loading)return <main className="p-10 text-center">Loading...</main>;
 return <main className="page-shell min-h-screen px-4 py-10"><div className="mx-auto max-w-6xl space-y-8"><section className="section-shell rounded-[2rem] p-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-orange-600">Admin Console</p><h1 className="mt-2 text-3xl font-semibold">Partner approvals & support</h1><Link href="/admin" className="mt-4 inline-block text-sm font-semibold text-slate-700">← Main admin dashboard</Link></section>{notice&&<p className="rounded-2xl bg-amber-50 p-4 text-amber-900">{notice}</p>}<section className="section-shell rounded-[2rem] p-7"><h2 className="text-2xl font-semibold">Sales-executive access</h2><p className="mt-2 text-sm text-slate-600">Ask the executive to sign in once at /partner/login, then activate that phone account here.</p><div className="mt-5 space-y-3">{staffUsers.map(s=><article key={s.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-4"><div><p className="font-semibold">{s.displayName||s.phoneNumber||s.email||"User account"}</p><p className="text-xs text-slate-500">{s.phoneNumber||s.email||s.id} · {s.role}</p></div><button onClick={()=>void setSalesRole(s,s.role!=="sales_executive")} className={s.role==="sales_executive"?"btn btn-outline btn-sm":"btn btn-primary btn-sm"}>{s.role==="sales_executive"?"Remove access":"Activate sales access"}</button></article>)}</div></section><section className="section-shell rounded-[2rem] p-7"><h2 className="text-2xl font-semibold">Assisted registrations</h2><div className="mt-5 space-y-3">{rows.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">{r.businessName}</p><p className="text-sm text-slate-500">{r.ownerName} · {r.phoneE164} · {r.city} · {r.category}</p><p className="mt-1 text-xs font-semibold uppercase text-slate-500">{statusLabel(r.status)}</p></div>{r.status!=="approved"&&<div className="flex gap-2"><button onClick={()=>void decide(r,"approved")} className="btn btn-primary btn-sm">Approve</button><button onClick={()=>void decide(r,"rejected")} className="btn btn-outline btn-sm">Reject</button></div>}</div></article>)}</div></section><section className="section-shell rounded-[2rem] p-7"><h2 className="text-2xl font-semibold">Support tickets</h2><div className="mt-5 space-y-3">{tickets.map(t=><article key={t.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-semibold">{t.subject}</p><p className="mt-1 text-sm text-slate-600">{t.message}</p><p className="mt-1 text-xs uppercase text-slate-500">{t.createdByRole||"user"} · {t.status}</p></div>{t.status!=="resolved"&&<button onClick={()=>void closeTicket(t)} className="btn btn-primary btn-sm">Resolve</button>}</div></article>)}</div></section></div></main>;
}
